# Generated by Django 4.2.23 on 2025-06-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Agotado', 'Agotado'), ('Preventa', 'Preventa')], default='Disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Polo', 'Polo'), ('Polera', 'Polera')], max_length=50),
        ),
    ]
